ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Create user
CREATE USER healthcare IDENTIFIED BY healthcare123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO healthcare;
GRANT CREATE SESSION TO healthcare;
GRANT CREATE TABLE TO healthcare;
GRANT CREATE SEQUENCE TO healthcare;
GRANT CREATE VIEW TO healthcare;

EXIT;
